before:
  hooks:
    - go generate .

builds:
  - binary: webexec
    id: non-darwin
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - binary: webexec
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
   - 
     id: darwin
     replace: true
     hooks: 
       post: gon gon.hcl

# darwin archive is a dmg defined in gon.hcl
archives:
  - 
    id: non-darwin
    builds:
      - non-darwin
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - webexec.service.tmpl
      - replace_n_launch.sh


checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
