#!/usr/bin/env bash
build_n_run() {
    docker compose -f $1  --project-directory . build
    docker compose -f $1  --project-directory . up --exit-code-from runner
}
if [ $# -eq 0 ]
then
    for compose in `find atp -name "lab.yaml"`
    do
        dir=$(dirname $compose)
        echo ">>> Setting a lab based on $dir"
        build_n_run $compose
        if [ $? -ne 0 ]
        then
            echo ">>> $dir tests FAILED"
             exit 4
        fi
    done
else
    npx vite build
    for arg in $@
    do
        echo ">>> Setting a lab based on $arg"
        build_n_run $arg/lab.yaml
        if [ $? -ne 0 ]
        then
             echo ">>> $arg FAILED"
             exit 4
        fi
        echo ">>> $arg tests PASSED"
    done
fi
